### ISSUE TITLE
error with p6spy driver

### ISSUE THREAD

**Issue by vaibhavpudke0007** [EMResearch/EvoMaster#275] opened 2021-04-04 10:03 UTC
Failed to retrieve SUT info. HTTP status 500. Error: 'SQL drivers are misconfigured. You must use a 'p6spy' wrapper when yo
u run the SUT. For example, a database connection URL like 'jdbc:h2:mem:testdb' should be changed into 'jdbc:p6spy:h2:mem:testdb'. See documentation on how to configure P6Spy.'

←[31m[ERROR] ←[0m←[33mERROR in the Remote EvoMaster Driver: Failed to retrieve the info about the system under test

**Comment by arcuri82** [comment] 2021-04-04 11:42
duplicate of #266

**Closed** 2021-04-04 11:42 UTC
