### ISSUE TITLE
(JDK above 8) Running EvoMaster against WebApplication fails with (for me) random ErrorMessage

### ISSUE THREAD

**Issue by schmori** [EMResearch/EvoMaster#635] opened 2022-10-28 22:31 UTC
javax.ws.rs.ProcessingException: java.lang.reflect.InaccessibleObjectException: Unable to make field protected java.lang.String java.net.HttpURLConnection.method accessible: module java.base does not "opens java.net" to unnamed module @2d58d9ed
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:309)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:630)
        at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:665)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:659)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
        at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:659)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:629)
        at org.evomaster.core.problem.rest.service.AbstractRestFitness.handleRestCall(AbstractRestFitness.kt:301)
        at org.evomaster.core.problem.rest.service.RestResourceFitness.doCalculateCoverage(RestResourceFitness.kt:76)
        at org.evomaster.core.problem.rest.service.RestResourceFitness.doCalculateCoverage(RestResourceFitness.kt:17)
        at org.evomaster.core.search.service.FitnessFunction.calculateIndividualWithPostHandling(FitnessFunction.kt:104)
        at org.evomaster.core.search.service.FitnessFunction.calculateCoverage(FitnessFunction.kt:56)
        at org.evomaster.core.search.service.FitnessFunction.calculateCoverage$default(FitnessFunction.kt:48)
        at org.evomaster.core.search.algorithms.MioAlgorithm.searchOnce(MioAlgorithm.kt:38)
        at org.evomaster.core.search.service.SearchAlgorithm.search(SearchAlgorithm.kt:66)
        at org.evomaster.core.Main$Companion.run(Main.kt:437)
        at org.evomaster.core.Main$Companion.initAndRun(Main.kt:150)
        at org.evomaster.core.Main$Companion.main(Main.kt:74)
        at org.evomaster.core.Main.main(Main.kt)
Caused by: java.lang.RuntimeException: java.lang.reflect.InaccessibleObjectException: Unable to make field protected java.lang.String java.net.HttpURLConnection.method accessible: module java.base does not "opens java.net" to unnamed module @2d58d9ed
        at org.glassfish.jersey.client.internal.HttpUrlConnector$3.run(HttpUrlConnector.java:518)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.glassfish.jersey.client.internal.HttpUrlConnector.setRequestMethodViaJreBugWorkaround(HttpUrlConnector.java:479)
        at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:323)
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:265)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:297)
        ... 21 common frames omitted
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field protected java.lang.String java.net.HttpURLConnection.method accessible: module java.base does not "opens java.net" to unnamed module @2d58d9ed
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at org.glassfish.jersey.client.internal.HttpUrlConnector$3.run(HttpUrlConnector.java:513)
        ... 26 common frames omitted

**Comment by arcuri82** [comment] 2022-10-28 22:46
`module java.base does not "opens [java.net](http://java.net/)" to unnamed module`  looks like you are using jar file directly (and not an installer), with JDK > 8. For JDKs above 8, please see the [documentation](https://github.com/EMResearch/EvoMaster/blob/master/docs/jdks.md)

but i guess we should catch this type of exceptions, and provide some explanatory info

**Comment by schmori** [comment] 2022-10-29 09:31
<img width="1091" alt="Bildschirmfoto 2022-10-29 um 11 27 07" src="https://user-images.githubusercontent.com/56094344/198824187-eaffa2ef-ff3b-48f4-945b-8f0c9020ddc2.png">

Thank you very much for your help and effort.

I already set some configs for the Driver with the menioned flag in he VM options...and I use jdk 14 since the application I want to run the EvoMaster against, does nt support jdk 8. But I guess I still do something wrong?

**Comment by arcuri82** [comment] 2022-10-29 21:48
that is for the driver. from the linked documentation:


>The recommended way to use EvoMaster is via its installer, e.g., .msi for Windows. However, you can still use its jar file directly, if you really want. Unfortunately, though, if you use JDK 17 or above, you have to deal with --add-opens shenanigans.
>
>To see how to set it up, look at the usage of --add-opens in [makeExecutable.sh](https://github.com/EMResearch/EvoMaster/blob/master/makeExecutable.sh) script.


which means you need as well `--add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED`.

From what you are reporting, it looks like the issue is same for JDK 14. However, noticed that: `We support JDK 8 and the major LTS versions after that (currently JDK 17). Might work on other JVM versions, but we provide NO support for it. `. JDK 14 is not LTS (8, 11 and 17 are).

**Comment by arcuri82** [comment] 2023-01-31 20:34
this is now fixed in the new 1.6.0 release, with error message specifying what to do in this case

**Closed by arcuri82** 2023-01-31 20:34 UTC
Labels: bug
