### ISSUE TITLE
Error When Run EmbeddedEvoMasterController

### ISSUE THREAD

**Issue by inoex135** [EMResearch/EvoMaster#180] opened 2020-05-21 02:12 UTC
I tried to run EmbbededEvoMasterController but I got these error messages:

_Exception in thread "main" java.lang.ExceptionInInitializerError
	at em.embedded.org.javiermf.features.EmbeddedEvoMasterController.main(EmbeddedEvoMasterController.java:36)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at shaded.com.ea.agentloader.AgentLoader$1.loadAgent(AgentLoader.java:244)
	at shaded.com.ea.agentloader.AgentLoader.loadAgent(AgentLoader.java:77)
	at shaded.com.ea.agentloader.AgentLoader.loadAgentClass(AgentLoader.java:148)
	at shaded.com.ea.agentloader.AgentLoader.loadAgentClass(AgentLoader.java:102)
	at org.evomaster.client.java.controller.InstrumentedSutStarter.<clinit>(InstrumentedSutStarter.java:23)
	... 1 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at shaded.com.ea.agentloader.AgentLoader$1.loadAgent(AgentLoader.java:240)
	... 5 more
Caused by: java.lang.RuntimeException: java.io.IOException: Can not attach to current VM
	at shaded.com.ea.agentloader.AgentLoaderHotSpot.getVirtualMachine(AgentLoaderHotSpot.java:90)
	at shaded.com.ea.agentloader.AgentLoaderHotSpot.loadAgent(AgentLoaderHotSpot.java:56)
	... 10 more
Caused by: java.io.IOException: Can not attach to current VM
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.<init>(HotSpotVirtualMachine.java:75)
	at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:57)
	at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:58)
	at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
	at shaded.com.ea.agentloader.AgentLoaderHotSpot.getVirtualMachine(AgentLoaderHotSpot.java:86)
	... 11 more_

Is there any hint how to solve this problem?

**Comment by inoex135** [comment] 2020-05-21 02:17
This problem was solved by changing jdk into 1.8. Previously I used jdk 14.

**Comment by inoex135** [comment] 2020-05-21 02:23
I tried to open http://localhost:40100/controller/api/ buat the response was 404
![evomaster-404](https://user-images.githubusercontent.com/244285/82516360-b67dca80-9b44-11ea-9e04-6e59048f9cbe.png)

**Comment by inoex135** [comment] 2020-05-21 07:54
Got this error message: 
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:156)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at em.embedded.org.javiermf.features.EmbeddedEvoMasterController.startSut(EmbeddedEvoMasterController.java:57)
	at org.evomaster.client.java.controller.internal.EMController.runSut(EMController.java:200)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at shaded.org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at shaded.org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at shaded.org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at shaded.org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at shaded.org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at shaded.org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at shaded.org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at shaded.org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at shaded.org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	at shaded.org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at shaded.org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at shaded.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at shaded.org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at shaded.org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at shaded.org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)
	at shaded.org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at shaded.org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)
	at shaded.org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)
	at shaded.org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at shaded.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at shaded.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at shaded.org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at shaded.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at shaded.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at shaded.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at shaded.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at shaded.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at shaded.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at shaded.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at shaded.org.eclipse.jetty.server.Server.handle(Server.java:503)
	at shaded.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at shaded.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at shaded.org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at shaded.org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at shaded.org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at shaded.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at shaded.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at shaded.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at shaded.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at shaded.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at shaded.org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getWebServerFactory(ServletWebServerApplicationContext.java:203)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:179)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:153)
	... 58 more

Btw, is it if I log all my problem here? Because I think this is a great project. If this project can be used easily, it will be a breakthrough to increase software quality

**Comment by arcuri82** [comment] 2020-05-21 09:06
Hi,
  thanks for reporting these issues.

1. as stated in the readme.md, EvoMaster (EM) only supports JDK 8 and 11, not 14. The problem you saw would appear in JDK 11 as well. There is a fix for it, but not implemented yet (it is complicated...). Current workaround is described  [here](https://github.com/EMResearch/EvoMaster/blob/master/docs/write_driver.md): you would need to use `-Djdk.attach.allowAttachSelf=true`
2. `/controller/api` has no web interface, so the 404 on its base path is expected. But I guess we should rather just return an HTML page there with some explanation
3. regarding your last point, I am not sure. it looks like your application is crashing when started. might be a misconfiguration on your side not depending of EM. does that application work if run directly? if the problem is related to EM, then the only explanation I could  think of is dependency clashing on the `javax.` package. we saw something like this in the past. you might want to try this:
```
  <dependency>
            <groupId>org.evomaster</groupId>
            <artifactId>evomaster-client-java-controller</artifactId>
            <version>${evomaster-version}</version>
            <exclusions>
                <exclusion>
                    <groupId>javax.validation</groupId>
                    <artifactId>validation-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
``` 
4. yes, please, report all issues you find :)  but of course we cannot guarantee when we can look at them, or provide a fix

**Comment by inoex135** [comment] 2020-05-21 09:31
point 3, my application running well if using mvn spring-boot:run command. 

can you give information spring boot version which is used in https://github.com/EMResearch/EvoMaster/blob/master/docs/write_driver.md ? 

I am using 2.2.1

**Comment by arcuri82** [comment] 2020-05-21 09:54
when u add `evomaster-client-java-controller`, I assume you have the `test` scope (as it should be). Can you try to remove the `<scope>test</scope>`  and then run `mvn spring-boot:run` to see if you get the same problem? (if the answer is yes, then it is a dependency mismatch issue)

**Comment by arcuri82** [comment] 2020-05-21 09:55
and the version of SpringBoot should not matter. EM is supposed to work independently from the application framework

**Comment by inoex135** [comment] 2020-05-21 10:12
Here is my pom.xml 
<dependency>
            <groupId>org.evomaster</groupId>
            <artifactId>evomaster-client-java-controller</artifactId>
            <version>LATEST</version>
        </dependency>

Is that you mean?

**Comment by arcuri82** [comment] 2020-05-21 11:50
ah, damn, just realized that one in the docs is missing the  `<scope>test</scope>`...

can you paste here your `public String startSut() {` implementation? just to see if i recognize any misconfiguration there

furthermore, have you looked at [this StackOverflow question](https://stackoverflow.com/questions/50231736/applicationcontextexception-unable-to-start-servletwebserverapplicationcontext)?  that might help in understanding what is going on here

**Comment by inoex135** [comment] 2020-06-19 03:57
Sorry, late response:

**Comment by arcuri82** [comment] 2020-06-19 12:09
Hi,
  I do not see anything wrong in that method (apart from fixing port `9091` instead of using an ephemeral `0`).

This seems like some Spring misconfiguration.
What happen if you try to run SpringBoot directly with a main method?
Eg, something like the following (added directly in the `Application` class):

```
  public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
 }
```

Do you see the same error?

**Comment by arcuri82** [comment] 2020-09-30 12:47
closed as no further info was provided

**Closed by arcuri82** 2020-09-30 12:47 UTC
