### ISSUE TITLE
Compiler error showing in the java file created within body section. 

### ISSUE THREAD

**Issue by agrawalhemant5393** [EMResearch/EvoMaster#687] opened 2023-01-15 08:50 UTC
Hi 
I have 3 files created: fault representative, faul, success. In the success test I am find syntax error in the created java file while re-running the created file

- > The body of the file have this syntax for one of the created test.  This happens when I am running the for more than 2 minutes.

This junit depency I am using to run JUNIT 4.
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13.2</version>
			<scope>test</scope>
		</dependency>

 
 
![image](https://user-images.githubusercontent.com/39014040/212531613-c71e0ad5-77e2-43b7-9aac-846f1ada3437.png)

**Comment by arcuri82** [comment] 2023-01-16 08:41
hi,
  what is the error message given by the compiler?

**Comment by agrawalhemant5393** [comment] 2023-01-18 05:00
Compiler error is:"String literal is not properly closed by a double-quote". And no error is displayed on console. Only test fails as shown in the image.

Issue details: Mainly body is having multiple double-inverted commas. So compiler is unable to detect the exact string. 

![image](https://user-images.githubusercontent.com/39014040/213087887-ac60d0b1-5c06-4a93-930d-1c206440286c.png)

**Comment by arcuri82** [comment] 2023-01-18 08:29
hi,
 thx. i see the issue. the content type is `x-www-form-urlencoded`, but then the body payload is wrongly formatted as a JSON, with wrong handling of `{`. 
could you share the OpenAPI specs of the endpoint `/api/shipping/get_fedex_rate`? is it by any chance a public API? (so I could look at it directly)

**Comment by agrawalhemant5393** [comment] 2023-01-18 15:33
Sorry, but it's not a public api. So, difficult to share it here.

**Comment by arcuri82** [comment] 2023-01-19 13:34
thanks for reporting this bug.

the issue seems related to the formatting of the `x-www-form-urlencoded` type when object inputs have no declared fields

**Comment by arcuri82** [comment] 2023-01-19 20:57
the issue is now fixed in the `master` branch.

**Comment by agrawalhemant5393** [comment] 2023-01-20 01:53
So will there be new jar file for evomaster tool? Is build uploaded or
ready to upload?

**Comment by arcuri82** [comment] 2023-01-20 07:58
you can either build snapshot locally, or download it from [GitHub Action](https://github.com/EMResearch/EvoMaster/actions/runs/3962304637)

**Comment by agrawalhemant5393** [comment] 2023-01-20 10:41
Thanks for solving this so quick.

**Comment by arcuri82** [comment] 2023-01-20 10:49
thx. i ll close the issue once the fix is out in the next release

**Comment by arcuri82** [comment] 2023-01-31 20:32
this is now fixed in the new 1.6.0 release.

**Closed by arcuri82** 2023-01-31 20:32 UTC
Labels: bug
