### ISSUE TITLE
 Black-box testing broken in v1.2.0

### ISSUE THREAD

**Issue by bestdd** [EMResearch/EvoMaster#335] opened 2021-06-28 14:16 UTC
command
 java -jar /Users/xxx/evomaster.jar  --blackBox true --bbSwaggerUrl http://localhost:6086/v2/api-docs  --outputFormat JAVA_JUNIT_4 --maxTime 60s

* EvoMaster version: 1.2.0
22:12:52.696 [main] WARN  org.evomaster.core.EMConfig - WARNING: you are doing Black-Box testing, but you did not specify the 'problemType'. The system will default to RESTful API testing.
22:12:53.947 [main] WARN  o.e.c.p.rest.RestActionBuilderV3 - No fields for object definition: body
* There are 3 usable RESTful API endpoints defined in the schema configuration
22:12:53.959 [main] WARN  o.e.c.p.rest.RestActionBuilderV3 - No fields for object definition: TestReqDto
* Starting to generate test cases
* Consumed search budget: 0.270%; covered targets: 0; time per test: 162.0ms (3.0 actions)
22:12:54.191 [main] WARN  o.e.c.s.service.SearchTimeController - The SUT sent a 'Connection: close' HTTP header. This should be avoided, if possible
* [ERROR] EvoMaster process terminated abruptly. This is likely a bug in EvoMaster. Please copy&paste the following stacktrace, and create a new issue on https://github.com/EMResearch/EvoMaster/issues
java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 1.
	at kotlin.collections.EmptyList.get(Collections.kt:35)
	at kotlin.collections.EmptyList.get(Collections.kt:23)
	at org.evomaster.core.problem.httpws.service.HttpWsFitness.getlocation5xx(HttpWsFitness.kt:160)
	at org.evomaster.core.problem.rest.service.AbstractRestFitness.handleResponseTargets(AbstractRestFitness.kt:206)
	at org.evomaster.core.problem.rest.service.BlackBoxRestFitness.doCalculateCoverage(BlackBoxRestFitness.kt:60)
	at org.evomaster.core.problem.rest.service.BlackBoxRestFitness.doCalculateCoverage(BlackBoxRestFitness.kt:17)
	at org.evomaster.core.search.service.FitnessFunction.calculateCoverage(FitnessFunction.kt:59)
	at org.evomaster.core.search.service.FitnessFunction.calculateCoverage$default(FitnessFunction.kt:46)
	at org.evomaster.core.search.algorithms.RandomAlgorithm.search(RandomAlgorithm.kt:25)
	at org.evomaster.core.Main$Companion.run(Main.kt:378)
	at org.evomaster.core.Main$Companion.initAndRun(Main.kt:149)
	at org.evomaster.core.Main$Companion.main(Main.kt:73)
	at org.evomaster.core.Main.main(Main.kt)

**Comment by arcuri82** [comment] 2021-06-29 11:41
thanks for reporting this bug ;)

indeed black-box testing is broken in version 1.2.0, due to a regression. please use 1.1.0 until we make a hot-fix

**Comment by bestdd** [comment] 2021-07-01 06:24
thanks

**Comment by arcuri82** [comment] 2021-07-01 06:28
issue should now be fixed in the new 1.2.1 release. thx

**Closed by arcuri82** 2021-07-01 06:28 UTC
Labels: bug

**Comment by bestdd** [comment] 2021-07-01 06:53
> issue should now be fixed in the new 1.2.1 release. thx

Passed
