### ISSUE TITLE
cannot get description by id (InstrumentationController.java  and ObjectiveRecorder.java)

### ISSUE THREAD

**Issue by ZhangMan1126** [EMResearch/EvoMaster#16] opened 2018-10-01 09:56 UTC
`Caused by: java.lang.IllegalArgumentException: Id '258' is not mapped
	at org.evomaster.clientJava.instrumentation.staticState.ObjectiveRecorder.getDescriptiveId(ObjectiveRecorder.java:230) ~[evomaster-client-java-controller-0.1.2-SNAPSHOT.jar:na]
	at org.evomaster.clientJava.instrumentation.InstrumentationController.lambda$getTargetInfos$0(InstrumentationController.java:47) ~[evomaster-client-java-controller-0.1.2-SNAPSHOT.jar:na]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553) ~[na:1.8.0_181]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[na:1.8.0_181]
	at org.evomaster.clientJava.instrumentation.InstrumentationController.getTargetInfos(InstrumentationController.java:45) ~[evomaster-client-java-controller-0.1.2-SNAPSHOT.jar:na]
	at org.evomaster.clientJava.controller.EmbeddedSutController.getTargetInfos(EmbeddedSutController.java:33) ~[evomaster-client-java-controller-0.1.2-SNAPSHOT.jar:na]
	at org.evomaster.clientJava.controller.internal.EMController.getTargets(EMController.java:158) ~[evomaster-client-java-controller-0.1.2-SNAPSHOT.jar:na]
	at sun.reflect.GeneratedMethodAccessor82.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]`

**Comment by arcuri82** [comment] 2018-10-01 09:59
thx. looks like a bug. on which SUT does it happen? does it happen all the time? or sporadically?

**Comment by ZhangMan1126** [comment] 2018-10-01 10:39
SCS case study. Actually, it only happened one time.

**Comment by arcuri82** [comment] 2019-03-31 13:44
i couldn't not reproduce it. however, there were some related issues in client code, which are now (hopefully) fixed. closing this issue. if it happens again, please re-open it ;)

**Closed by arcuri82** 2019-03-31 13:44 UTC
