### ISSUE TITLE
Need some details

### ISSUE THREAD

**Issue by aldiak** [EMResearch/EvoMaster#174] opened 2020-04-28 05:12 UTC
Hi, I am currently trying evomaster but I didn,t understand the documentation at all, because It is said to download evomaster.jar and when It is downloaded where to place It (not mentioned in the documentation) and when I am using EMB to generate test cases with this command mvn clean install -DskipTests I am getting Snapshot error. So if you could actually explain the whole process clearly. Thanks

**Comment by arcuri82** [comment] 2020-04-28 13:00
Hi,
  thanks for trying out EvoMaster.
- regarding downloading: it can be anywhere, it does not matter, as long as you can run it in a terminal. I ll update the documentation to explain it
- your second point should had been already covered in the readme of [EMB](https://github.com/EMResearch/EMB): 

> Note: the case studies do import EvoMaster as a library. Current SNAPSHOT versions of the case studies do use the most recent SNAPSHOT version of EvoMaster (the two versioning numbers are aligned). We do NOT publish the SNAPSHOT dependencies online. This means that, if you try to build the project directly, it will fail due to missing SNAPSHOT dependencies.

> To use such SNAPSHOT versions, you need first a mvn install of EvoMaster on your machine (so that the SNAPSHOT jars are created, and put under your ~/.m2 folder). However, in the Git repository of EMB, we did tag the versions of EMB that are using the published versions of EvoMaster. See the releases page. For example, to use version X of EvoMaster, you can check out the Git commit of EMB tagged with version X.

**Comment by aldiak** [comment] 2020-04-28 19:50
Thanks for the answer, now regarding the mvn install of Evomaster, how
should I have that because I thought installing maven was enought.

**Comment by arcuri82** [comment] 2020-04-29 10:30
sorry, but I am not sure I understand your question. Can you please provide some more details? In general, are you familiar with how build tools like Maven and Gradle work?

**Comment by aldiak** [comment] 2020-04-29 11:40
In general no, but have gradle in Android studio.
My problem is I have downloaded EMB and Evomaster.jar. I have installed
maven but when I tried to run mvn clean install... I am getting a snapshot
error so I am kinda lost.

Le mercredi 29 avril 2020, Andrea Arcuri <notifications@github.com> a
écrit :

**Comment by arcuri82** [comment] 2020-04-29 14:48
assuming you have downloaded the most recent version of evomaster.jar (v1.0.1), then, in the folder where you cloned the EMB repository, run the following:

`git checkout tags/v1.0.1`

after that, `mvn install -DskipTests` there should work fine

**Comment by arcuri82** [comment] 2020-04-29 14:58
I just added the following to the documentation

>To see the current available tags, from a command-line you can execute:
>
>`git tag`
>
>Then, to switch to a specific tag X (e.g., `v1.0.0`), you can run:
>
>`git checkout tags/v1.0.0`
>
>Finally, if for any reason you need to swith back to the latest snapshot version, you can run:
>
>`git checkout master`

**Comment by aldiak** [comment] 2020-04-29 17:25
Hi, sorry for all but I am still getting error with It.

Le mercredi 29 avril 2020, Andrea Arcuri <notifications@github.com> a
écrit :

**Comment by aldiak** [comment] 2020-04-29 17:35
You can these log.

**Comment by arcuri82** [comment] 2020-04-29 17:38
what logs? where are they?

**Comment by aldiak** [comment] 2020-04-30 02:30
I attached some pictures in my previews email.

**Comment by arcuri82** [comment] 2020-04-30 11:06
it appears you are answering via email. GitHub ignores all email attachments. you need to paste the text of the logs as part of the messages here  https://github.com/EMResearch/EvoMaster/issues/174

**Comment by aldiak** [comment] 2020-04-30 11:53
here are the error message:


[INFO] --- maven-apt-plugin:1.0:process (default) @ features-service ---
[ERROR] execute error
java.lang.NullPointerException
    at com.mysema.maven.apt.AbstractProcessorMojo.execute (AbstractProcessorMojo.java:127)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (Unknown Source)
    at java.lang.reflect.Method.invoke (Unknown Source)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] features-service 1.0.1-SNAPSHOT .................... FAILURE [  1.262 s]
[INFO] scout-api 1.0-SNAPSHOT ............................. SKIPPED
[INFO] data-access 1.0-SNAPSHOT ........................... SKIPPED
[INFO] auth 1.0-SNAPSHOT .................................. SKIPPED
[INFO] data-batch-jobs 1.0-SNAPSHOT ....................... SKIPPED
[INFO] api 1.0-SNAPSHOT ................................... SKIPPED
[INFO] ProxyPrint-kitchen 1.0-SNAPSHOT .................... SKIPPED
[INFO] org.zalando:catwatch 0.0.1-SNAPSHOT ................ SKIPPED
[INFO] catwatch-backend 0.0.1-SNAPSHOT .................... SKIPPED
[INFO] EvoMaster Benchmark (EMB) 1.0.1 .................... SKIPPED
[INFO] evomaster-benchmark-cs 1.0.1 ....................... SKIPPED
[INFO] evomaster-benchmark-cs-rest 1.0.1 .................. SKIPPED
[INFO] evomaster-benchmark-cs-rest-original 1.0.1 ......... SKIPPED
[INFO] evomaster-benchmark-cs-rest-artificial 1.0.1 ....... SKIPPED
[INFO] evomaster-benchmark-cs-rest-artificial-ncs 1.0.1 ... SKIPPED
[INFO] evomaster-benchmark-cs-rest-artificial-scs 1.0.1 ... SKIPPED
[INFO] evomaster-benchmark-cs-rest-artificial-news 1.0.1 .. SKIPPED
[INFO] OCVN 1.3.0-SNAPSHOT ................................ SKIPPED
[INFO] OCVN Persistence 1.3.0-SNAPSHOT .................... SKIPPED
[INFO] OCVN MongoDB Persistence 1.3.0-SNAPSHOT ............ SKIPPED
[INFO] OCVN Web 1.3.0-SNAPSHOT ............................ SKIPPED
[INFO] OCVN UI 1.3.0-SNAPSHOT ............................. SKIPPED
[INFO] OCVN Forms 1.3.0-SNAPSHOT .......................... SKIPPED
[INFO] evomaster-benchmark-cs-rest-gui 1.0.1 .............. SKIPPED
[INFO] evomaster-benchmark-em 1.0.1 ....................... SKIPPED
[INFO] evomaster-benchmark-em-external 1.0.1 .............. SKIPPED
[INFO] evomaster-benchmark-em-external-rest 1.0.1 ......... SKIPPED
[INFO] evomaster-benchmark-em-external-rest-features-service 1.0.1 SKIPPED
[INFO] evomaster-benchmark-em-external-rest-scout-api 1.0.1 SKIPPED
[INFO] evomaster-benchmark-em-external-rest-proxyprint 1.0.1 SKIPPED
[INFO] evomaster-benchmark-em-external-rest-ncs 1.0.1 ..... SKIPPED
[INFO] evomaster-benchmark-em-external-rest-scs 1.0.1 ..... SKIPPED
[INFO] evomaster-benchmark-em-external-rest-catwalk 1.0.1 . SKIPPED
[INFO] evomaster-benchmark-em-external-rest-news 1.0.1 .... SKIPPED
[INFO] evomaster-benchmark-em-external-rest-ind0 1.0.1 .... SKIPPED
[INFO] evomaster-benchmark-em-external-rest-ocvn 1.0.1 .... SKIPPED
[INFO] evomaster-benchmark-em-embedded 1.0.1 .............. SKIPPED
[INFO] evomaster-benchmark-em-embedded-rest 1.0.1 ......... SKIPPED
[INFO] evomaster-benchmark-em-embedded-rest-features-service 1.0.1 SKIPPED
[INFO] evomaster-benchmark-em-embedded-rest-scout-api 1.0.1 SKIPPED
[INFO] evomaster-benchmark-em-embedded-rest-proxyprint 1.0.1 SKIPPED
[INFO] evomaster-benchmark-em-embedded-rest-ncs 1.0.1 ..... SKIPPED
[INFO] evomaster-benchmark-em-embedded-rest-scs 1.0.1 ..... SKIPPED
[INFO] evomaster-benchmark-em-embedded-rest-catwatch 1.0.1  SKIPPED
[INFO] evomaster-benchmark-em-embedded-rest-news 1.0.1 .... SKIPPED
[INFO] evomaster-benchmark-em-embedded-rest-ocvn 1.0.1 .... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.250 s
[INFO] Finished at: 2020-04-30T19:52:14+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.mysema.maven:maven-apt-plugin:1.0:process (default) on project features-service: null: MojoExecutionException -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by arcuri82** [comment] 2020-04-30 12:54
haven't seen that error before, and I cannot reproduce it on my machine.
Question: are you building with JDK 8? What do you get if you run `mvn --version`?

Furthermore, you do not need to build EMB with Maven from command line. If you want to try it out, you can simply open EMB with an IDE (eg IntelliJ or Eclipse), and then directly start one of the `EmbeddedEvoMasterController` classes

**Comment by aldiak** [comment] 2020-04-30 13:08
I am getting this version:
C:\Users\Alou>mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\apache-maven-3.6.3\bin\..
Java version: 1.8.0_221, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jre1.8.0_221
Default locale: fr_FR, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by arcuri82** [comment] 2020-04-30 13:24
that's very weird... the Maven and JDK versions should be fine.
here you are getting a NPE in a Maven plugin...
We have been building EMB on Windows 10 machines in the past, so that should not be the problem.

The only thing I can think of is if you have any space or special character in the folder path of where you cloned EMB.

Btw, what happens if you try to build from an IDE (eg if you try to start one of `EmbeddedEvoMasterController`, like the one for features-service)?

**Comment by aldiak** [comment] 2020-04-30 13:41
I got these if I build from Intellij:

Error:(6, 36) java: cannot find symbol
  symbol:   class QProduct
  location: package org.javiermf.features.models

Error:(7, 36) java: cannot find symbol
  symbol:   class QProductConfiguration
  location: package org.javiermf.features.models

Error:(21, 5) java: cannot find symbol
  symbol:   class QProductConfiguration
  location: class org.javiermf.features.daos.ProductsConfigurationsDAO

Error:(22, 5) java: cannot find symbol
  symbol:   class QProduct
  location: class org.javiermf.features.daos.ProductsConfigurationsDAO

Error:(21, 51) java: cannot find symbol
  symbol:   variable QProductConfiguration
  location: class org.javiermf.features.daos.ProductsConfigurationsDAO

Error:(22, 25) java: cannot find symbol
  symbol:   variable QProduct
  location: class org.javiermf.features.daos.ProductsConfigurationsDAO

Error:(35, 9) java: cannot find symbol
  symbol:   class QProduct
  location: class org.javiermf.features.daos.ProductsConfigurationsDAO

Error:(35, 29) java: cannot find symbol
  symbol:   variable QProduct
  location: class org.javiermf.features.daos.ProductsConfigurationsDAO

C:\Users\Alou\Desktop\EMB\cs\rest\original\featuresservice\src\main\java\org\javiermf\features\daos\ProductsDAO.java
Error:(8, 36) java: cannot find symbol
  symbol:   class QFeature
  location: package org.javiermf.features.models

Error:(9, 36) java: cannot find symbol
  symbol:   class QProduct
  location: package org.javiermf.features.models

Error:(11, 48) java: cannot find symbol
  symbol:   class QFeatureConstraint
  location: package org.javiermf.features.models.constraints

Error:(25, 5) java: cannot find symbol
  symbol:   class QProduct
  location: class org.javiermf.features.daos.ProductsDAO

Error:(26, 5) java: cannot find symbol
  symbol:   class QFeature
  location: class org.javiermf.features.daos.ProductsDAO

Error:(27, 5) java: cannot find symbol
  symbol:   class QFeatureConstraint
  location: class org.javiermf.features.daos.ProductsDAO

Error:(25, 25) java: cannot find symbol
  symbol:   variable QProduct
  location: class org.javiermf.features.daos.ProductsDAO

Error:(26, 25) java: cannot find symbol
  symbol:   variable QFeature
  location: class org.javiermf.features.daos.ProductsDAO

Error:(27, 45) java: cannot find symbol
  symbol:   variable QFeatureConstraint
  location: class org.javiermf.features.daos.ProductsDAO

**Comment by arcuri82** [comment] 2020-04-30 13:49
those are the files that are supposed to be created by that Maven plugin.

in `cs/rest/original/features-service/pom.xml`, can you try to update the plugin version of `apt-maven-plugin` from 1.0 to `1.1.3` and see if that is of any help?

furthermore, what is the path from root (i guess `C:\` in your case) of where you cloned EMB? (if there are spaces or special non-ASCII charcters there, it could be an issue)

**Comment by aldiak** [comment] 2020-04-30 13:54
the path is like that    C:\Users\Alou\Desktop\EMB

**Comment by arcuri82** [comment] 2020-04-30 14:00
the path is fine, there is no special character there.
did updating to 1.1.3 help?

**Comment by arcuri82** [comment] 2020-04-30 14:08
i see. what happens if you try 1.1?

**Comment by aldiak** [comment] 2020-04-30 14:13
Now It is that this pluging spring-boot-maven-plugin is not find, but still updating.

**Comment by arcuri82** [comment] 2020-05-03 16:02
what problem are you getting with spring-boot-maven-plugin?

**Comment by aldiak** [comment] 2020-05-11 15:07
It is saying this:  Cannot resolve
org.evomaster:evomaster-client-java-instrumentation:1.0.2-SNAPSHOT

Le lun. 4 mai 2020 à 00:02, Andrea Arcuri <notifications@github.com> a
écrit :

**Comment by arcuri82** [comment] 2020-05-14 11:58
if you get an error related to 1.0.2-SNAPSHOT, that means you are building EMB directly without having done a "mvn install" for EvoMaster repository.

But, if you want to use 1.0.1 version (ie the already built Jar on GitHub), on EMB rep you need to do a "git checkout tags/v1.0.1", as stated in previous message

**Comment by arcuri82** [comment] 2020-09-30 12:50
closed as no further info was provided

**Closed by arcuri82** 2020-09-30 12:50 UTC
