### ISSUE TITLE
EvoMaster process terminated abruptly

### ISSUE THREAD

**Issue by HanzhenLu** [EMResearch/EvoMaster#914] opened 2024-02-29 12:54 UTC
It's strange that it can deal with URL successfully but always fails for local files even they have the same content.

```
20:41:23.556 [main] WARN  o.t.u.TestcontainersConfiguration - Attempted to read Testcontainers configuration file at file:/home/lhz/.testcontainers.properties but the file was not found. Exception message: FileNotFoundException: /home/{usr}/.testcontainers.properties (No such file or directory)
* [ERROR] EvoMaster process terminated abruptly. This is likely a bug in EvoMaster. Please copy&paste the following stacktrace, and create a new issue on https://github.com/EMResearch/EvoMaster/issues
```

If there are stacktraces of the errors, please paste them here.
```
java.lang.reflect.InvocationTargetException: invokedynamic: method=public void org.evomaster.core.problem.rest.service.AbstractRestSampler.initialize(), target=org.evomaster.core.problem.rest.service.RestSampler@4fcee388
        at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:316)
        at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:298)
        at com.netflix.governator.lifecycle.LifecycleManager.startInstance(LifecycleManager.java:266)
        at com.netflix.governator.lifecycle.LifecycleManager.add(LifecycleManager.java:175)
        at com.netflix.governator.guice.InternalLifecycleModule.onProvision(InternalLifecycleModule.java:81)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113)
        at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:239)
        at com.netflix.governator.guice.LifecycleInjector.createChildInjector(LifecycleInjector.java:331)
        at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:411)
        at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:352)
        at org.evomaster.core.Main$Companion.init(Main.kt:385)
        at org.evomaster.core.Main$Companion.initAndRun(Main.kt:160)
        at org.evomaster.core.Main$Companion.main(Main.kt:84)
        at org.evomaster.core.Main.main(Main.kt)
Caused by: java.lang.IllegalArgumentException: URI has an authority component
        at sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:53)
        at sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:98)
        at java.nio.file.Paths.get(Paths.java:138)
        at org.evomaster.core.problem.rest.OpenApiAccess.readFromDisk(OpenApiAccess.kt:67)
        at org.evomaster.core.problem.rest.OpenApiAccess.getOpenAPIFromURL(OpenApiAccess.kt:45)
        at org.evomaster.core.problem.rest.service.AbstractRestSampler.initForBlackBox(AbstractRestSampler.kt:252)
        at org.evomaster.core.problem.rest.service.AbstractRestSampler.initialize(AbstractRestSampler.kt:61)
        at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:313)
        ... 26 common frames omitted
```
Other important info:
- version of EvoMaster (EM) used ：**2.0**
- how EM is run (eg, if from JAR or from one of its OS installers) : **jar**
- version of applicable runtimes (eg, JVM, NodeJS and .Net). For Java, can paste the output of `java --version` : 
    **java version "1.8.0_391"
    Java(TM) SE Runtime Environment (build 1.8.0_391-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 25.391-b13, mixed mode)**
- command-line options used to run EM : 
    **java -jar evomaster.jar  --blackBox true --bbSwaggerUrl file://specifications/test.yaml  --outputFormat JAVA_JUNIT_4 --maxTime 30s --ratePerMinute 60**

**Comment by arcuri82** [comment] 2024-02-29 20:43
hi,
 thanks for reporting this bug. it looks like a duplicate of #701, which should be fixed in snapshot version. 
The error is in your URL, although EM gives a not so nice error message. 
Try rather to use `file:///specifications/test.yaml` (note the extra `/`)

**Closed** 2024-04-05 12:32 UTC
Labels: bug, FIXED in SNAPSHOT

**Comment by arcuri82** [comment] 2025-03-23 10:56
Dear @HanzhenLu ,

  thanks for trying out EvoMaster and opening an issue here. If you have 10 minutes, we would be grateful if you could fill this survey on test naming strategies #1206. We will use such information to improve EvoMaster. Thanks!
